spring.application.name=pharmacy-service
server.port=8081

spring.config.import=optional:configserver:http://localhost:8888

spring.kafka.bootstrap-servers=localhost:9092
pharmacy.kafka.topic.stock-events=medicine-stock-events

app.branch-name=Local
app.hotline=0000
pharmacy.vat-rate=10
pharmacy.e-invoice.gateway-url=http://127.0.0.1:1/e-invoice/mock