spring.application.name=pharmacy-service
server.port=8081

# Spring config
spring.config.import=configserver:http://localhost:8888

# Auto refresh dung cho RefreshScope
management.endpoints.web.exposure.include=refresh